# .github/workflows/build-domains.yml
name: Build domains.json from Airtable

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AT_BASE: appxLxgRbkXd31y9w   # Your Airtable Base ID
      AT_TABLE: Domains            # Table name
      # AT_VIEW: Grid view         # Optional: set exactly if you want to filter by a view
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Airtable -> data/domains.json
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          set -euo pipefail
          mkdir -p data
          python3 - <<'PY'
          import json, os, urllib.parse, urllib.request

          BASE   = os.environ["AT_BASE"]
          TABLE  = os.environ["AT_TABLE"]
          VIEW   = os.environ.get("AT_VIEW")  # may be None
          TOKEN  = os.environ["AIRTABLE_TOKEN"]

          def q(s): 
              return urllib.parse.quote(s)

          def fetch_all(base, table, view=None):
              api = f"https://api.airtable.com/v0/{base}/{q(table)}"
              params = "?pageSize=100"
              if view:
                  params += f"&view={q(view)}"
              headers = { "Authorization": f"Bearer {TOKEN}" }
              out = []
              url = api + params
              while True:
                  req = urllib.request.Request(url, headers=headers)
                  with urllib.request.urlopen(req) as resp:
                      data = json.loads(resp.read().decode("utf-8"))
                  out.extend(data.get("records", []))
                  off = data.get("offset")
                  if not off:
                      break
                  url = api + params + "&offset=" + q(off)
              return out

          def to_text(v):
              """Normalize Airtable values (strings, numbers, lists, dicts) into a display string."""
              if v is None:
                  return ""
              if isinstance(v, str):
                  return v.strip()
              if isinstance(v, (int, float, bool)):
                  return str(v)
              if isinstance(v, list):
                  return ", ".join(to_text(x) for x in v if x is not None)
              if isinstance(v, dict):
                  return v.get("name") or v.get("label") or json.dumps(v, ensure_ascii=False)
              return str(v)

          records = fetch_all(BASE, TABLE, VIEW)

          out_map = {}
          skipped = 0
          for r in records:
              f = r.get("fields", {})
              dn    = to_text(f.get("DomainName")).lower()
              if not dn:
                  continue

              # Only include if Sell? is True
              if not f.get("Sell?"):
                  skipped += 1
                  continue

              price = to_text(f.get("Sell Price"))
              note  = to_text(f.get("Sell Note"))
              group = to_text(f.get("Domain Group"))
              seo   = to_text(f.get("SEO Keywords"))
              uses  = to_text(f.get("Use-cases"))

              out_map[dn] = {
                  "price": price,
                  "note": note,
                  "domain-group": group,
                  "seo-keywords": seo,
                  "use-cases": uses,
              }

          with open("data/domains.json","w",encoding="utf-8") as fp:
              json.dump(out_map, fp, ensure_ascii=False, indent=2)

          print(f"Generated data/domains.json with {len(out_map)} domains; skipped {skipped}.")
          PY

      - name: Preview JSON
        run: |
          echo "First lines of data/domains.json:"
          head -n 30 data/domains.json || true

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/domains.json
          git diff --cached --quiet && { echo "No changes"; exit 0; }
          git commit -m "Update domains.json from Airtable"
          git push
